/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import com.mongodb.AutoEncryptionSettings;
import com.mongodb.ClientEncryptionSettings;
import com.mongodb.ConnectionString;
import com.mongodb.MongoClientSettings;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.CreateCollectionOptions;
import com.mongodb.client.model.Filters;
import com.mongodb.client.model.Sorts;
import com.mongodb.client.model.vault.DataKeyOptions;
import com.mongodb.client.model.vault.EncryptOptions;
import com.mongodb.client.model.vault.RangeOptions;
import com.mongodb.client.result.InsertManyResult;
import com.mongodb.client.vault.ClientEncryption;
import com.mongodb.client.vault.ClientEncryptions;
import org.bson.BsonArray;
import org.bson.BsonBinary;
import org.bson.BsonDocument;
import org.bson.BsonInt32;
import org.bson.BsonInt64;
import org.bson.BsonString;
import org.bson.BsonValue;
import org.bson.conversions.Bson;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import static java.util.Arrays.asList;

public class ExplicitEncryptionMixedFieldsMixedCollections {

    private static final String ENCRYPTED_FIELD_1 = "encryptedInt";
    private static final String ENCRYPTED_FIELD_2 = "encryptedLong";

    public static void main(String[] args) {
        System.out.println("============================");
        System.out.println("         STARTING");
        System.out.println("============================");

        String mongoConnectionString = args.length == 0 ? "mongodb://localhost:27017" : args[0];

        // This would have to be the same master key as was used to create the encryption key
        byte[] localMasterKey = new byte[96];
        new SecureRandom().nextBytes(localMasterKey);

        Map<String, Map<String, Object>> kmsProviders = new HashMap<>() {
            {
                put("local", new HashMap<>() {
                    {
                        put("key", localMasterKey);
                    }
                });
            }
        };

        String keyVaultNamespace = "encryption.__keyVault";
        ClientEncryptionSettings clientEncryptionSettings = ClientEncryptionSettings.builder()
                .keyVaultMongoClientSettings(MongoClientSettings.builder()
                        .applyConnectionString(new ConnectionString(mongoConnectionString))
                        .build())
                .keyVaultNamespace(keyVaultNamespace)
                .kmsProviders(kmsProviders)
                .build();

        try (ClientEncryption clientEncryption = ClientEncryptions.create(clientEncryptionSettings)) {
            BsonBinary dataKeyId1 = clientEncryption.createDataKey("local", new DataKeyOptions());
            BsonBinary dataKeyId2 = clientEncryption.createDataKey("local", new DataKeyOptions());

            RangeOptions rangeOptionsQE = new RangeOptions()
                    .min(new BsonInt32(0))
                    .max(new BsonInt32(200))
                    .trimFactor(1)
                    .sparsity(1L);

            EncryptOptions encryptValueOptionsQE = new EncryptOptions("Range")
                    .keyId(dataKeyId1)
                    .contentionFactor(0L)
                    .rangeOptions(rangeOptionsQE);

            EncryptOptions encryptExpressionOptionsQE = new EncryptOptions("Range")
                    .keyId(dataKeyId1)
                    .queryType("Range")
                    .contentionFactor(0L)
                    .rangeOptions(rangeOptionsQE);

            EncryptOptions encryptValueOptionsCSFLE = new EncryptOptions("AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic")
                    .keyId(dataKeyId2);

            MongoClientSettings clientSettings = MongoClientSettings.builder()
                    .autoEncryptionSettings(AutoEncryptionSettings.builder()
                            .keyVaultNamespace(keyVaultNamespace)
                            .kmsProviders(kmsProviders)
                            .bypassAutoEncryption(false) // use libmongocrypt (apache 2.0)
                            .bypassQueryAnalysis(true) // bypass mongocryptd and crypt_shared
                            .build()) // Auto encryption settings are required
                    .build();

            try (MongoClient mongoClient = MongoClients.create(clientSettings)) {
                String databaseName = "testExplicitEncryption";
                String collectionNameQE = "explicit_qe_encryption";
                String collectionNameCSFLE = "explicit_csfle_encryption";

                MongoDatabase database = mongoClient.getDatabase(databaseName);
                database.drop();
                MongoCollection<BsonDocument> collectionQE = database.getCollection(collectionNameQE, BsonDocument.class);
                MongoCollection<BsonDocument> collectionCSFLE = database.getCollection(collectionNameCSFLE, BsonDocument.class);

                BsonDocument encryptedFieldsQE = new BsonDocument()
                        .append(
                                "fields",
                                new BsonArray(asList(
                                        new BsonDocument("keyId", dataKeyId1)
                                                .append("path", new BsonString(ENCRYPTED_FIELD_1))
                                                .append("bsonType", new BsonString("int"))
                                                .append(
                                                        "queries",
                                                        new BsonDocument("queryType", new BsonString("range"))
                                                                .append("contention", new BsonInt64(0L))
                                                                .append("trimFactor", new BsonInt32(1))
                                                                .append("sparsity", new BsonInt64(1))
                                                                .append("min", new BsonInt32(0))
                                                                .append("max", new BsonInt32(200))))));

                database.createCollection(
                        collectionNameQE, new CreateCollectionOptions().encryptedFields(encryptedFieldsQE));


                BsonDocument encryptedFieldsCSFLE = new BsonDocument()
                        .append(
                                "fields",
                                new BsonArray(asList(
                                        new BsonDocument("keyId", dataKeyId2)
                                                .append("path", new BsonString(ENCRYPTED_FIELD_2))
                                                .append("bsonType", new BsonString("long")))));

                database.createCollection(collectionNameCSFLE);

                // Explicitly encrypt a field
                System.out.println("\n  > Inserting some data in QE collection");
                List<BsonDocument> documents = IntStream.range(1, 10)
                        .boxed()
                        .map(i -> new BsonDocument("_id", new BsonInt32(i))
                                .append(
                                        ENCRYPTED_FIELD_1,
                                        encryptValue(clientEncryption, new BsonInt32(i), encryptValueOptionsQE)))
                        .toList();
                System.out.println(documents);
                InsertManyResult insertManyResult = collectionQE.insertMany(documents);
                System.out.println(
                        "    Inserted: " + insertManyResult.getInsertedIds().size() + " documents.");

                System.out.println("\n  > Example of the data without decryption:\n");
                System.out.println(collectionQE.find().into(new ArrayList<>()).stream()
                        .map(BsonDocument::toJson)
                        .collect(Collectors.joining(",\n    ", "    ", "\n")));

                System.out.println("\n  > Finding the data within a range using encryptExpression:\n");

                Bson encryptExpression1 = Filters.and(Filters.gte(ENCRYPTED_FIELD_1, 5));

                BsonDocument encryptedQueryQE =
                        encryptExpression(clientEncryption, encryptExpression1, encryptExpressionOptionsQE);

                System.out.println(
                        collectionQE.find(encryptedQueryQE).sort(Sorts.ascending("_id")).into(new ArrayList<>()).stream()
                                .map(BsonDocument::toJson)
                                .collect(Collectors.joining(",\n    ", "    ", "\n")));

                System.out.println("\n ====================== \n");
                System.out.println("\n  > Inserting some data in CSFLE collection");
                List<BsonDocument> documentsCSFLE = IntStream.range(1, 10)
                        .boxed()
                        .map(i -> new BsonDocument("_id", new BsonInt32(i))
                                .append(
                                        ENCRYPTED_FIELD_2,
                                        encryptValue(clientEncryption, new BsonInt64(i), encryptValueOptionsCSFLE)))
                        .toList();
                System.out.println(documentsCSFLE);
                InsertManyResult insertManyResultCSFLE = collectionCSFLE.insertMany(documentsCSFLE);
                System.out.println(
                        "    Inserted: " + insertManyResultCSFLE.getInsertedIds().size() + " documents.");

                System.out.println("\n  > Example of the data:\n");
                System.out.println(collectionCSFLE.find().into(new ArrayList<>()).stream()
                        .map(BsonDocument::toJson)
                        .collect(Collectors.joining(",\n    ", "    ", "\n")));

                System.out.println("\n  > Finding the data via CSFLE encryptedLong == 5L:\n");

                Bson encryptExpressionCSFLE = Filters.eq(ENCRYPTED_FIELD_2, encryptValue(clientEncryption, new BsonInt64(5), encryptValueOptionsCSFLE));

                System.out.println(
                        collectionCSFLE.find(encryptExpressionCSFLE).sort(Sorts.ascending("_id")).into(new ArrayList<>()).stream()
                                .map(BsonDocument::toJson)
                                .collect(Collectors.joining(",\n    ", "    ", "\n")));
            }
        }

        System.out.println("============================");
        System.out.println("         fin.");
        System.out.println("============================");
        System.out.println("\n");
    }

    private static BsonValue encryptValue(
            ClientEncryption clientEncryption, BsonValue value, EncryptOptions encryptOptions) {
        return clientEncryption.encrypt(value, encryptOptions);
    }

    private static BsonDocument encryptExpression(
            ClientEncryption clientEncryption, Bson expression, EncryptOptions encryptOptions) {
        return clientEncryption.encryptExpression(expression, encryptOptions);
    }
}
